version: '3.8'

services:
  hub:
    image: selenium/hub:4.0.0
    ports:
      - "4444:4444"

  node-firefox:
    image: selenium/node-firefox:4.0.0
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PORT=4442
    shm_size: 2g
